### ISSUE TITLE
Composer version not up to date

### ISSUE THREAD

**Issue by marekdedic** [cebe/markdown-latex#12]
I was having issues with tables when I found out, that the version I got with composer isn't the most recent one...

Could you please fix this?

T. Y.

**Comment by cebe** [comment]
what exactly is the problem, what should be fixed?

**Comment by GenaBitu** [comment]
The issue for me was that if a table row has empty leading cells, those would be stripped, So that this:
```markdown
| Row1 | Row 2 |
| | value |
```
would render as

| Row1 | Row 2 |
| --- | --- |
| value |

I found this issue while using cebe/markdown-latex I got from composer. However, when I replaced cebe/markdown-latex and (more importantly) cebe/markdown with the version from GitHub master, this issue was no longer present.
I think it has to do with markdown-latex (latest) depending on markdown 1.0.0 whereas this issue was fixed in 1.1.0. I am not sure though.

Thanks

**Comment by cebe** [comment]
thanks, will check that.

**Comment by samwilson** [comment]
This looks like it's fixed now.
